import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
        en: {
            "title": "Cromberg - personal finance accounting system",
            "income": "Income",
            "balance": "Balance",
            "settings": "Settings",
            "remind": "Remind me every month about balance",
            "remind_email": "E-mail for reminds",
            "sum": "Sum",
            "max_sum": "Max sum",
            "average": "Average",
            "top_month": "Best month",
            "worst_month": "Worst month",
            "date": "Date of receive money",
            "month": "Month",
            "type": "Type",
            "contact": "Contact",
            "description": "Description",
            "balance_source_input": "Enter a place to storage money",
            "save": "Save",
            "income_month": "Income by month",
            "income_year": "Income by year",
            "income_average": "Average income by year",
            "income_by_type": "By types",
            "income_by_contact": "By contacts",
            "backup_folder": "Backup folder",
            "database_folder": "Database folder",
            "choose_folder": "Choose folder",
            "balance_chart_title": "Balance by months",
            "balance_chart_diff_title": "Diff with previous month",
            "balance_pie_chart_title": "Last month: ?",
            "costs_chart_title": "Costs by months",
            "cost": "Spending",
            "no_internet": "Its need internet connection for correct work",
            "language": "Language",
            "statistic": "Statistic",
            "new_version": "A new version of the application has been released. Current: ?, new: ?.",
            "balance_sum": "Sum"
        },
        ru: {
            "title": "Cromberg - система личного учёта",
            "income": "Доход",
            "balance": "Баланс",
            "settings": "Настройки",
            "remind": "Присылать мне уведомления каждый месяц",
            "remind_email": "E-mail для уведомлений",
            "sum": "Сумма",
            "max_sum": "Максимальная сумма",
            "average": "Средний",
            "top_month": "Лучший месяц",
            "worst_month": "Худший месяц",
            "date": "Дата поступления средств",
            "month": "Месяц",
            "type": "Тип",
            "contact": "Контакт",
            "description": "Описание",
            "balance_source_input": "Введите место для хранения средств",
            "save": "Сохранить",
            "income_month": "Доход по месяцам",
            "income_year": "Доход по годам",
            "income_average": "Средний доход по годам",
            "income_by_type": "По типам",
            "income_by_contact": "По контактам",
            "backup_folder": "Папка для бекапов",
            "database_folder": "Папка для базы данных",
            "choose_folder": "Выберите папку",
            "balance_chart_title": "Баланс по месяцам",
            "balance_chart_diff_title": "Разница с предыдущим месяцем",
            "balance_pie_chart_title": "За последний месяц: ?",
            "costs_chart_title": "Расход по месяцам",
            "cost": "Расход",
            "no_internet": "Без подключения к интернету работа программы невозможна",
            "language": "Язык",
            "statistic": "Статистика",
            "new_version": "Вышла новая версия приложения. Текущая версия: ?, новая версия: ?.",
            "balance_sum": "Сумма"
        },
        fr: {
            "title": "Cromberg - système de comptabilité financière personnelle",
            "income": "Revenu",
            "balance": "Balance",
            "settings": "Paramètres",
            "remind": "Rappelez-moi chaque mois la balance",
            "remind_email": "E-mail de rappel",
            "sum": "Somme",
            "max_sum": "Max sum",
            "average": "Moyenne",
            "top_month": "Meilleur mois",
            "worst_month": "Pire mois",
            "date": "Date de réception de l'argent",
            "month": "Mois",
            "type": "Type",
            "contact": "Contact",
            "description": "Description",
            "balance_source_input": "Entrer un endroit pour ranger de l'argent",
            "save": "Enregister",
            "income_month": "Revenu mensuel",
            "income_year": "Revenu annuel",
            "income_average": "Revenu moyen annuel",
            "income_by_type": "Par types",
            "income_by_contact": "Par des contacts",
            "backup_folder": "Dossier de sauvegarde",
            "database_folder": "Dossier de la base de données ",
            "choose_folder": "Choisissez dossier",
            "balance_chart_title": "Balance par mois",
            "balance_chart_diff_title": "Balance par mois",
            "balance_pie_chart_title": "Le mois dernier: ?",
            "costs_chart_title": "Coûts par mois",
            "cost": "Déchets",
            "no_internet": "Connexion internet nécessaire pour fonctionné correctement",
            "language": "Langue",
            "statistic": "Statistique",
            "new_version": "Une nouvelle version de l'application a été publiée. Actuel:?, nouveau:?.",
            "balance_sum": "Somme"
        }
    }
);

export default strings;